apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: mtier
spec:
  volumeName: mongo-pv
  storageClassName: standered
  accessModes: 
    - ReadWriteOnce
  resources:
    requests: 
      storage: 1Gi
          